### ISSUE TITLE
2021.12.1更新后集成无法正常工作

### ISSUE THREAD

**Issue by AltracasysHC** [fineemb/xiaomi-cloud#10]
可能有用的官方说明：https://www.home-assistant.io/blog/2021/12/11/release-202112/#updates-for-custom-integration-developers

2021.12.1 报错日志：

Logger: homeassistant.components.device_tracker
Source: helpers/device_registry.py:366
Integration: 设备跟踪器 (documentation, issues)
First occurred: 23:05:09 (2 occurrences)
Last logged: 23:05:09

Error adding entities for domain device_tracker with platform xiaomi_cloud
Error while setting up xiaomi_cloud platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 500, in _async_add_entity
    device = device_registry.async_get_or_create(**processed_dev_info)  # type: ignore[arg-type]
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 366, in async_get_or_create
    entry_type = DeviceEntryType(entry_type)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'device' is not a valid DeviceEntryType

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 15:04:02 (6 occurrences)
Last logged: 15:04:30

Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue to the custom component author for xiaomi_cloud using this method at custom_components/xiaomi_cloud/__init__.py, line 182: with async_timeout.timeout(15, loop=self.hass.loop):
Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue to the custom component author for xiaomi_cloud using this method at custom_components/xiaomi_cloud/__init__.py, line 201: with async_timeout.timeout(15, loop=self.hass.loop):
Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue to the custom component author for xiaomi_cloud using this method at custom_components/xiaomi_cloud/__init__.py, line 219: with async_timeout.timeout(15, loop=self.hass.loop):
Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue to the custom component author for xiaomi_cloud using this method at custom_components/xiaomi_cloud/__init__.py, line 244: with async_timeout.timeout(15, loop=self.hass.loop):
Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue to the custom component author for xiaomi_cloud using this method at custom_components/xiaomi_cloud/__init__.py, line 354: with async_timeout.timeout(15, loop=self.hass.loop):

**Comment by ChuanzhaoZhang** [comment]
作者尽快更新吧
