### ISSUE TITLE
致后来者，此仓库作者长期未更新适配新版homeassistant，我Fork修复了获得sign失败的bug

### ISSUE THREAD

**Issue by rslywhj** [fineemb/xiaomi-cloud#14]
请移步https://github.com/rslywhj/xiaomi-cloud

**Comment by superabbite1** [comment]
怎么用啊，集成已经安装了。连个手册也木有 一头雾水

**Comment by monster-xxx** [comment]
> 请移步 https://github.com/rslywhj/xiaomi-cloud

大哥牛逼 登录上了

**Comment by monster-xxx** [comment]
> 请移步 https://github.com/rslywhj/xiaomi-cloud



> 请移步 https://github.com/rslywhj/xiaomi-cloud

023-11-27 03:33:08.126 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up xiaomi_cloud platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_cloud/device_tracker.py", line 35, in async_setup_entry
    for i in range(len(coordinator.data)):
                   ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'bool' has no len()
2023-11-27 03:33:19.273 DEBUG (MainThread) [custom_components.xiaomi_cloud] Username: 
2023-11-27 03:33:19.273 DEBUG (MainThread) [custom_components.xiaomi_cloud] Data will be update every 1:00:00
2023-11-27 03:33:19.274 DEBUG (MainThread) [custom_components.xiaomi_cloud] service: None
2023-11-27 03:33:19.275 WARNING (MainThread) [custom_components.xiaomi_cloud] timeout() got an unexpected keyword argument 'loop'
2023-11-27 03:33:19.275 WARNING (MainThread) [custom_components.xiaomi_cloud] get_sign Failed
2023-11-27 03:33:19.275 DEBUG (MainThread) [custom_components.xiaomi_cloud] Finished fetching xiaomi_cloud data in 0.001 seconds (success: True)
2023-11-27 03:33:19.278 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up xiaomi_cloud platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_cloud/device_tracker.py", line 35, in async_setup_entry
    for i in range(len(coordinator.data)):
                   ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'bool' has no len()

**Comment by uncle-wong** [comment]
> > 请移步 https://github.com/rslywhj/xiaomi-cloud
> 
> > 请移步 https://github.com/rslywhj/xiaomi-cloud
> 
> 023-11-27 03:33:08.126 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up xiaomi_cloud platform for device_tracker Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform await asyncio.shield(task) File "/config/custom_components/xiaomi_cloud/device_tracker.py", line 35, in async_setup_entry for i in range(len(coordinator.data)): ^^^^^^^^^^^^^^^^^^^^^ TypeError: object of type 'bool' has no len() 2023-11-27 03:33:19.273 DEBUG (MainThread) [custom_components.xiaomi_cloud] Username: 2023-11-27 03:33:19.273 DEBUG (MainThread) [custom_components.xiaomi_cloud] Data will be update every 1:00:00 2023-11-27 03:33:19.274 DEBUG (MainThread) [custom_components.xiaomi_cloud] service: None 2023-11-27 03:33:19.275 WARNING (MainThread) [custom_components.xiaomi_cloud] timeout() got an unexpected keyword argument 'loop' 2023-11-27 03:33:19.275 WARNING (MainThread) [custom_components.xiaomi_cloud] get_sign Failed 2023-11-27 03:33:19.275 DEBUG (MainThread) [custom_components.xiaomi_cloud] Finished fetching xiaomi_cloud data in 0.001 seconds (success: True) 2023-11-27 03:33:19.278 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up xiaomi_cloud platform for device_tracker Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform await asyncio.shield(task) File "/config/custom_components/xiaomi_cloud/device_tracker.py", line 35, in async_setup_entry for i in range(len(coordinator.data)): ^^^^^^^^^^^^^^^^^^^^^ TypeError: object of type 'bool' has no len()

我也是这样的

**Comment by lyj0309** [comment]
> > > 请移步 https://github.com/rslywhj/xiaomi-cloud
> > 
> > 
> > > 请移步 https://github.com/rslywhj/xiaomi-cloud
> > 
> > 
> > 023-11-27 03:33:08.126 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up xiaomi_cloud platform for device_tracker Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform await asyncio.shield(task) File "/config/custom_components/xiaomi_cloud/device_tracker.py", line 35, in async_setup_entry for i in range(len(coordinator.data)): ^^^^^^^^^^^^^^^^^^^^^ TypeError: object of type 'bool' has no len() 2023-11-27 03:33:19.273 DEBUG (MainThread) [custom_components.xiaomi_cloud] Username: 2023-11-27 03:33:19.273 DEBUG (MainThread) [custom_components.xiaomi_cloud] Data will be update every 1:00:00 2023-11-27 03:33:19.274 DEBUG (MainThread) [custom_components.xiaomi_cloud] service: None 2023-11-27 03:33:19.275 WARNING (MainThread) [custom_components.xiaomi_cloud] timeout() got an unexpected keyword argument 'loop' 2023-11-27 03:33:19.275 WARNING (MainThread) [custom_components.xiaomi_cloud] get_sign Failed 2023-11-27 03:33:19.275 DEBUG (MainThread) [custom_components.xiaomi_cloud] Finished fetching xiaomi_cloud data in 0.001 seconds (success: True) 2023-11-27 03:33:19.278 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up xiaomi_cloud platform for device_tracker Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform await asyncio.shield(task) File "/config/custom_components/xiaomi_cloud/device_tracker.py", line 35, in async_setup_entry for i in range(len(coordinator.data)): ^^^^^^^^^^^^^^^^^^^^^ TypeError: object of type 'bool' has no len()
> 
> 我也是这样的

又修复了一版本，可以试试
https://github.com/lyj0309/xiaomi-cloud.git
